name: Edward
favicon: null
layout_spectrum: 0.10609
typography_spectrum: 0.40634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8072811136953533
  lightness: 0.3112262364011258
  saturation: 0.11638814629986882
  rhythmicContrast: 0.6763129148166627
purpose: []
